require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '18.0'

target 'mlDemo' do
  config = use_native_modules!
  pod 'TensorFlowLite', '1.12.0'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'mlDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  #post_install do |installer|
  #  react_native_post_install(installer)
  #end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 18.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        end
      end
    end
    react_native_post_install(installer)
  end
end